#!/bin/bash

julia poincare_invariant_2nd/guiding_center_4d_fast_poincare_invariant_2nd_vprk_dt1.jl
julia poincare_invariant_2nd/guiding_center_4d_fast_poincare_invariant_2nd_vprk_dt2.jl
julia poincare_invariant_2nd/guiding_center_4d_fast_poincare_invariant_2nd_vprk_dt5.jl
julia poincare_invariant_2nd/guiding_center_4d_fast_poincare_invariant_2nd_vprk_dt10.jl

julia poincare_invariant_2nd/guiding_center_4d_symmetric_poincare_invariant_2nd_vprk_dt1.jl
julia poincare_invariant_2nd/guiding_center_4d_symmetric_poincare_invariant_2nd_vprk_dt2.jl
julia poincare_invariant_2nd/guiding_center_4d_symmetric_poincare_invariant_2nd_vprk_dt5.jl
julia poincare_invariant_2nd/guiding_center_4d_symmetric_poincare_invariant_2nd_vprk_dt10.jl
