#!/bin/bash

julia poincare_invariant_1st/guiding_center_4d_fast_poincare_invariant_1st_vprk_dt1.jl
julia poincare_invariant_1st/guiding_center_4d_fast_poincare_invariant_1st_vprk_dt2.jl
julia poincare_invariant_1st/guiding_center_4d_fast_poincare_invariant_1st_vprk_dt5.jl
julia poincare_invariant_1st/guiding_center_4d_fast_poincare_invariant_1st_vprk_dt10.jl

julia poincare_invariant_1st/guiding_center_4d_symmetric_poincare_invariant_1st_vprk_dt1.jl
julia poincare_invariant_1st/guiding_center_4d_symmetric_poincare_invariant_1st_vprk_dt2.jl
julia poincare_invariant_1st/guiding_center_4d_symmetric_poincare_invariant_1st_vprk_dt5.jl
julia poincare_invariant_1st/guiding_center_4d_symmetric_poincare_invariant_1st_vprk_dt10.jl
