#!/bin/bash

julia guiding_center_4d_fast_poincare_invariant_1st_firk_dt1.jl
julia guiding_center_4d_fast_poincare_invariant_1st_firk_dt2.jl
julia guiding_center_4d_fast_poincare_invariant_1st_firk_dt5.jl
julia guiding_center_4d_fast_poincare_invariant_1st_firk_dt10.jl
