#!/bin/bash

julia tokamak_fast_particles/guiding_center_4d_fast_barely_passing_firk.jl
julia tokamak_fast_particles/guiding_center_4d_fast_barely_trapped_firk.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_passing_firk.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_trapped_firk.jl

julia tokamak_fast_particles/guiding_center_4d_fast_barely_passing_firk_comp.jl
julia tokamak_fast_particles/guiding_center_4d_fast_barely_trapped_firk_comp.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_passing_firk_comp.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_trapped_firk_comp.jl

julia tokamak_fast_particles/guiding_center_4d_fast_barely_passing_vprk.jl
julia tokamak_fast_particles/guiding_center_4d_fast_barely_trapped_vprk.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_passing_vprk.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_trapped_vprk.jl

julia tokamak_fast_particles/guiding_center_4d_fast_barely_passing_vprk_comp.jl
julia tokamak_fast_particles/guiding_center_4d_fast_barely_trapped_vprk_comp.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_passing_vprk_comp.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_trapped_vprk_comp.jl

julia tokamak_fast_particles/guiding_center_4d_fast_barely_passing_vprk_quad.jl
julia tokamak_fast_particles/guiding_center_4d_fast_barely_trapped_vprk_quad.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_passing_vprk_quad.jl
julia tokamak_fast_particles/guiding_center_4d_fast_deeply_trapped_vprk_quad.jl

./run_poincare_1st_firk.sh
./run_poincare_1st_vprk.sh
./run_poincare_2nd_firk.sh
./run_poincare_2nd_vprk.sh
